In [2]:
def count_vowel(s):
    
    vowels='aeiou'
    s=s.lower()
    count=0

    for ch in s:
        if ch in vowels:
            count+=1
    return count 

s="abhishkek"
ko=count_vowel(s)
print(ko)


3


In [3]:
def longest_unique_substring(s):
    longest = ""   # store longest substring
    n = len(s)

    # check all substrings
    for i in range(n):
        seen = set()   # store visited chars
        current = ""
        for j in range(i, n):
            if s[j] in seen:
                break  # repeat mila to break
            seen.add(s[j])
            current += s[j]
            if len(current) > len(longest):
                longest = current
    return longest, len(longest)


# Example
print(longest_unique_substring("abcabcbb"))  # ('abc', 3)
print(longest_unique_substring("pwwkew"))    # ('wke', 3)
print(longest_unique_substring("bbbbb"))     # ('b', 1)


('abc', 3)
('wke', 3)
('b', 1)


In [6]:
s = "  hello world  "
s.strip()           # "hello world"
s.split()           # ["hello","world"]
"-".join(["a","b"]) # "a-b"
s.replace(" ", "_") # "__hello_world__"  (replace all)
print(s)
"banana".count("an")# 2
"hello".find("l")   # 2 (first index) ; -1 if not found
print(s)

  hello world  
  hello world  


In [8]:
s="     kkk"
s.strip()



'kkk'

In [14]:
def is_palindorome(s):
    i=0
    j=len(s)-1
    while i<j:
     if s[i] !=s[j]:
        return False
    i+=1
    j-=1
    return True

s="abccba"

print(is_palindorome(s))

KeyboardInterrupt: 

In [15]:
def many_args(*args):
    return sum(args)

def config(**kwargs):
    for k,v in kwargs.items():
        print(k, v)

many_args(1,2,3)                # 6
config(timeout=10, debug=True)


timeout 10
debug True


In [19]:
##maps

 ##def cube(x):
    ##return x*x*x


l=[1,2,3,4]
newl=list(map(lambda x:x*x*x,l))
print(newl)

[1, 8, 27, 64]


In [20]:
###filter

def filter_f(a):
    return a>4

l=[1,2,3,4,5,6,7,8]
newl=list(filter(lambda x:x>4,l))
print(newl)

[5, 6, 7, 8]


In [21]:
## reduce

 from functools import reduce
  

IndentationError: unexpected indent (4168399707.py, line 2)

In [22]:
def factorial(n):
    if n <= 1: return 1
    return n * factorial(n-1)


In [23]:
def reverse(s):
    letter=[ch for ch in s if ch.isalpha()]
    results=[]
    for ch in s:
        if ch.isalpha():
            results.append(letter.pop())
        else:
            results.append(ch)
        
    return "".join(results)

s="a-vk-klo-lo"
print(reverse(s))

o-lo-lkk-va


In [24]:
from collections import Counter

def first_unique_char(s):
    count = Counter(s)
    for ch in s:
        if count[ch] == 1:
            return ch
    return None

print(first_unique_char("leetcode"))  # l
print(first_unique_char("aabb"))      # None


l
None


In [25]:
def compress_string(s):
    result = ""
    count = 1
    for i in range(1, len(s)+1):
        if i < len(s) and s[i] == s[i-1]:
            count += 1
        else:
            result += s[i-1] + str(count)
            count = 1
    return result

print(compress_string("aaabbc"))  # a3b2c1


a3b2c1


In [36]:

import numpy as np 


def ques1(A, B):
    print("Original A:\n", A)
    print("Original B:\n", B)

    # Step a + b: Sum of A and B
    S = A + B
    print("\nSum of A and B:\n", S)

    # Check row sum equality
    row_sums = np.sum(S, axis=1)
    if np.all(row_sums == row_sums[0]):   # all row sums same
        print("\nAll row sums same:", row_sums)

    np.fill_diagonal(S, -np.diag(S))
    print("\nAfter negating diagonal:\n", S)


    max_val=np.max(S)
    np.fill_diagonal(S,max_val)
    print("\nAfter replacing diagonal with max element:\n", S)

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print(sum(A,B))

org a
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
org a
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [38]:
import numpy as np

def is_prime(n):
    if n<2:
        return False
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
        return True
    
def ques2(A,B):

    for i in range(min(A.shape)):
        if A[i,i]%3!=0:
            A[i,i]=-A[i,i]
    print(A)

    min_val=np.min(B)
    for i in range(min(B.shape)):
        if is_prime(B[i,i]):
            B[i,i]=min_val
    print(B)
   
    if A.shape[1]==B.shape[0]:
        m=A @ B
        print(m)
        print("is symmetric?",np.array_equal(m,m.T))


A = np.array([[3,2,1],[4,5,6],[7,8,9]])
B = np.array([[2,3,5],[6,7,11],[13,17,19]])
ques2(A, B)


[[ 3  2  1]
 [ 4 -5  6]
 [ 7  8  9]]
[[ 2  3  5]
 [ 6  2 11]
 [13 17  2]]
[[ 31  30  39]
 [ 56 104 -23]
 [179 190 141]]
is symmetric? False


In [45]:
import numpy as np 
r1=int(input("enter r1"))
c1=int(input("enter c1"))

elements=list(map(float,input().split()))
a=np.array(elements).reshape(r1,c1)
print(a)

det=np.linalg.det(a)
print(det)

[[1. 2.]
 [3. 4.]]
-2.0000000000000004
